config/routes.rb
Iproject::Application.routes.draw do
  resources :reports

  resources :items_solds

  resources :items_boughts

  resources :products

end

app/models/items_bought.rb
class ItemsBought < ActiveRecord::Base
  belongs_to :product
end

app/controllers/items_boughts_controller.rb
class ItemsBoughtsController < ApplicationController
  before_action :set_items_bought, only: [:show, :edit, :update, :destroy]

  # GET /items_boughts
  # GET /items_boughts.json
  def index
    @items_boughts = ItemsBought.all
  end

  # GET /items_boughts/1
  # GET /items_boughts/1.json
  def show
  end

  # GET /items_boughts/new
  def new
    @items_bought = ItemsBought.new
  end

  # GET /items_boughts/1/edit
  def edit
  end

  # POST /items_boughts
  # POST /items_boughts.json
  def create
    @items_bought = ItemsBought.new(items_bought_params)

    respond_to do |format|
      if @items_bought.save
        format.html { redirect_to @items_bought, notice: 'Items bought was successfully created.' }
        format.json { render action: 'show', status: :created, location: @items_bought }
      else
        format.html { render action: 'new' }
        format.json { render json: @items_bought.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items_boughts/1
  # PATCH/PUT /items_boughts/1.json
  def update
    respond_to do |format|
      if @items_bought.update(items_bought_params)
        format.html { redirect_to @items_bought, notice: 'Items bought was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @items_bought.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items_boughts/1
  # DELETE /items_boughts/1.json
  def destroy
    @items_bought.destroy
    respond_to do |format|
      format.html { redirect_to items_boughts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_items_bought
      @items_bought = ItemsBought.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def items_bought_params
      params.require(:items_bought).permit(:ProductID, :AmountBought, :DateIn)
    end
end

app/helpers/items_boughts_helper.rb
module ItemsBoughtsHelper
end

app/views/items_boughts/_form.html.erb
<%= form_for(@items_bought) do |f| %>
  <% if @items_bought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@items_bought.errors.count, "error") %> prohibited this items_bought from being saved:</h2>

      <ul>
      <% @items_bought.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ProductID %><br>
    <%= f.collection_select :ProductID, Product.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :AmountBought %><br>
    <%= f.number_field :AmountBought %>
  </div>
  <div class="field">
    <%= f.label :DateIn %><br>
    <%= f.date_select :DateIn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items_boughts/edit.html.erb
<h1>Editing items_bought</h1>

<%= render 'form' %>

<%= link_to 'Show', @items_bought %> |
<%= link_to 'Back', items_boughts_path %>

app/views/items_boughts/index.html.erb
<h1>Items Bought</h1>

<table>
  <thead>
    <tr>
      <th>Product Id</th>
      <th>Amount Bought</th>
      <th>Date In</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items_boughts.each do |items_bought| %>
      <tr>
        <td><%= items_bought.ProductID %></td>
        <td><%= items_bought.AmountBought %></td>
        <td><%= items_bought.DateIn %></td>
        <td><%= link_to 'Show', items_bought %></td>
        <td><%= link_to 'Edit', edit_items_bought_path(items_bought) %></td>
        <td><%= link_to 'Destroy', items_bought, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Items bought', new_items_bought_path %>

app/views/items_boughts/new.html.erb
<h1>New items_bought</h1>

<%= render 'form' %>

<%= link_to 'Back', items_boughts_path %>

app/views/items_boughts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Productid:</strong>
  <%= @items_bought.ProductID %>
</p>

<p>
  <strong>Amountbought:</strong>
  <%= @items_bought.AmountBought %>
</p>

<p>
  <strong>Datein:</strong>
  <%= @items_bought.DateIn %>
</p>

<%= link_to 'Edit', edit_items_bought_path(@items_bought) %> |
<%= link_to 'Back', items_boughts_path %>