config/routes.rb
Iproject::Application.routes.draw do
  resources :reports

  resources :items_solds

  resources :items_boughts

  resources :products

end

app/models/items_sold.rb
class ItemsSold < ActiveRecord::Base
  belongs_to :product
end

app/controllers/items_solds_controller.rb
class ItemsSoldsController < ApplicationController
  before_action :set_items_sold, only: [:show, :edit, :update, :destroy]

  # GET /items_solds
  # GET /items_solds.json
  def index
    @items_solds = ItemsSold.all
  end

  # GET /items_solds/1
  # GET /items_solds/1.json
  def show
  end

  # GET /items_solds/new
  def new
    @items_sold = ItemsSold.new
  end

  # GET /items_solds/1/edit
  def edit
  end

  # POST /items_solds
  # POST /items_solds.json
  def create
    @items_sold = ItemsSold.new(items_sold_params)

    respond_to do |format|
      if @items_sold.save
        format.html { redirect_to @items_sold, notice: 'Items sold was successfully created.' }
        format.json { render action: 'show', status: :created, location: @items_sold }
      else
        format.html { render action: 'new' }
        format.json { render json: @items_sold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items_solds/1
  # PATCH/PUT /items_solds/1.json
  def update
    respond_to do |format|
      if @items_sold.update(items_sold_params)
        format.html { redirect_to @items_sold, notice: 'Items sold was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @items_sold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items_solds/1
  # DELETE /items_solds/1.json
  def destroy
    @items_sold.destroy
    respond_to do |format|
      format.html { redirect_to items_solds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_items_sold
      @items_sold = ItemsSold.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def items_sold_params
      params.require(:items_sold).permit(:ProductID, :amountSold, :Revenue, :dateOut)
    end
end

app/helpers/items_solds_helper.rb
module ItemsSoldsHelper
end

app/views/items_solds/_form.html.erb
<%= form_for(@items_sold) do |f| %>
  <% if @items_sold.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@items_sold.errors.count, "error") %> prohibited this items_sold from being saved:</h2>

      <ul>
      <% @items_sold.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ProductID %><br>
    <%= f.collection_select :ProductID, Product.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :amountSold %><br>
    <%= f.number_field :amountSold %>
  </div>
  <div class="field">
    <%= f.label :Revenue %><br>
    <%= f.text_field :Revenue %>
  </div>
  <div class="field">
    <%= f.label :dateOut %><br>
    <%= f.date_select :dateOut %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items_solds/edit.html.erb
<h1>Editing items_sold</h1>

<%= render 'form' %>

<%= link_to 'Show', @items_sold %> |
<%= link_to 'Back', items_solds_path %>

app/views/items_solds/index.html.erb
<h1>Items Sold</h1>

<table>
  <thead>
    <tr>
      <th>Product Id</th>
      <th>Amount Sold</th>
      <th>Revenue</th>
      <th>Date Out</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items_solds.each do |items_sold| %>
      <tr>
        <td><%= items_sold.ProductID %></td>
        <td><%= items_sold.amountSold %></td>
        <td><%= number_to_currency(items_sold.Revenue)%></td>
        <td><%= items_sold.dateOut %></td>
        <td><%= link_to 'Show', items_sold %></td>
        <td><%= link_to 'Edit', edit_items_sold_path(items_sold) %></td>
        <td><%= link_to 'Destroy', items_sold, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Items sold', new_items_sold_path %>

app/views/items_solds/new.html.erb
<h1>New items_sold</h1>

<%= render 'form' %>

<%= link_to 'Back', items_solds_path %>

app/views/items_solds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Productid:</strong>
  <%= @items_sold.ProductID %>
</p>

<p>
  <strong>Amountsold:</strong>
  <%= @items_sold.amountSold %>
</p>

<p>
  <strong>Revenue:</strong>
  <%= @items_sold.Revenue %>
</p>

<p>
  <strong>Dateout:</strong>
  <%= @items_sold.dateOut %>
</p>

<%= link_to 'Edit', edit_items_sold_path(@items_sold) %> |
<%= link_to 'Back', items_solds_path %>